### ISSUE TITLE
Has anyone made this work?

### ISSUE THREAD

**Issue by michaeljgilmore** [vlad-ghita/multiple_uploads#1]
I really am intrigued by what this extension can do but the documentation on how to get the mapper working didn't change anything at all.  Is there more detailed documentation  somewhere for this?

**Comment by vlad-ghita** [comment]
1. What exactly didn't work?
2. What's your `Child` section (eg: `Images`)?
3. What are the fields in that section?
4. What's your `Parent` section?
5. Is there a SBL+ in `Parent` pointing to `Child`?
6. Is the [SBL+](https://github.com/vlad-ghita/selectbox_link_field_plus) extension the one from my fork?

**Comment by DaveRev** [comment]
I'm trying this extension, but I get an error when I try to upload images:
Error SyntaxError: Unexpected token C 
I set this extension as default (with Images section, mapper, etc).

**Comment by vlad-ghita** [comment]
You need to know PHP to use this. Look at the mapper for Images section and modify it to suit your needs. It **will not** work out of the box.
